arm_controller:
  ros__parameters:
    joints:
      - base_to_torso
      - torso_to_arm

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    interpolate_from_desired_state: true

    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 5.0

      base_to_torso:
        goal: 0.02

      torso_to_arm:
        goal: 0.02
